podSecurityContext: {}
certificate:
  dnsNames:
  - "podinfo"
  create: false
  issuerRef:
    kind: "ClusterIssuer"
    name: "self-signed"
serviceMonitor:
  additionalLabels: {}
  interval: "15s"
  enabled: false
securityContext: {}
podAnnotations: {}
faults:
  delay: false
  unhealthy: false
  testTimeout: false
  error: false
  unready: false
  testFail: false
redis:
  tag: "7.0.7"
  repository: "redis"
  enabled: false
nodeSelector: {}
replicaCount: 1
extraArgs: []
linkerd:
  profile:
    enabled: false
tolerations: []
logLevel: "info"
ui:
  color: "#34577c"
  logo: ""
  message: ""
host: null
h2c:
  enabled: false
hpa:
  maxReplicas: 10
  memory: null
  cpu: null
  requests: null
  enabled: false
podDisruptionBudget: {}
backend: null
probes:
  readiness:
    failureThreshold: 3
    timeoutSeconds: 5
    periodSeconds: 10
    successThreshold: 1
    initialDelaySeconds: 1
  startup:
    failureThreshold: 20
    enable: false
    timeoutSeconds: 5
    periodSeconds: 10
    successThreshold: 1
    initialDelaySeconds: 10
  liveness:
    failureThreshold: 3
    timeoutSeconds: 5
    periodSeconds: 10
    successThreshold: 1
    initialDelaySeconds: 1
image:
  tag: "sha-c5ce34bc"
  repository: "ghcr.io/dfl-aeb/podinfo"
  pullPolicy: "IfNotPresent"
cache: ""
topologySpreadConstraints: []
resources:
  requests:
    memory: "16Mi"
    cpu: "1m"
  limits: null
serviceAccount:
  imagePullSecrets: []
  name: null
  enabled: false
backends: []
ingress:
  hosts:
  - paths:
    - path: "/"
      pathType: "ImplementationSpecific"
    host: "192.168.49.2.podinfo-dev.noip.io"
  additionalLabels: {}
  annotations: {}
  className: ""
  tls: []
  enabled: true
service:
  httpPort: 9898
  grpcPort: 9999
  annotations: {}
  hostPort: null
  type: "ClusterIP"
  nodePort: 31198
  enabled: true
  metricsPort: 9797
  externalPort: 9898
  grpcService: "podinfo"
extraEnvs: []
tls:
  secretName: null
  certPath: "/data/cert"
  port: 9899
  hostPort: null
  enabled: false
config:
  path: ""
  name: ""
affinity: {}
