name: cve-scan (disabled)

on:
  workflow_dispatch:

# Disabled: removed push/pull_request triggers to prevent automatic runs.

permissions:
  contents: read

jobs:
  govulncheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Vulnerability scan
        id: govulncheck
        uses: golang/govulncheck-action@v1
